services:
  - type: web
    name: my-frontend
    env: static
    staticPublishPath: frontend/build
    buildCommand: cd frontend && npm install && npm run build

  - type: web
    name: my-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
